### PR TITLE
Rename package name from io.airlift to com.facebook.airlift

### PR DESCRIPTION
**Pull request by wenleix**
Similar to https://github.com/prestodb/slice/pull/1 and https://github.com/prestodb/drift/pull/2

### CODE REVIEW

**Comment by aweisberg** [comment]
Huh. Do we really want to do this? This is unnecessary pain when attempting to cherry-pick commits from the other repo. Should consider reverting this change in the others?

I guess the associated pain is when dependencies use other versions of airlift, but then maybe shadowing is the answer? I guess it depends on what we want to optimize for. Ease of keeping up to date vs the occasional pain that comes from having to shadow a dependency.

**Comment by wenleix** [comment]
@aweisberg : I think it's OK for now just change the artifact name but not the package name. This would actually make changing dependencies easier :) 

We should then rename the package name back for drift and slice. cc @hellium01

**Comment by wenleix** [comment]
Superseded by https://github.com/prestodb/airlift/pull/4

**Comment by wenleix** [comment]
According to Maven convention: https://maven.apache.org/guides/mini/guide-naming-conventions.html , package name should be consistent with maven group+artifact id. 

Revive this PR.

**Pull request merged**
