### PR TITLE
use https for jquery

### PR DESCRIPTION
**Pull request by tooptoop4**
use https for jquery https://github.com/prestodb/presto/issues/13693

### CODE REVIEW

**Comment by tooptoop4** [comment]
gentle ping @wenleix

**Comment by tooptoop4** [comment]
cla bot

**Comment by wenleix** [comment]
@tooptoop4  : If you just sign the CLA after the PR is out, you probably need to do a force push to trigger the CLA bot again :)

**Comment by tooptoop4** [comment]
flaky test?
2020-01-08T21:48:07.552Z	INFO	main	org.eclipse.jetty.server.handler.ContextHandler	Stopped o.e.j.s.ServletContextHandler@dd737ea{/,null,UNAVAILABLE}
6139[ERROR] Tests run: 429, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 49.215 s <<< FAILURE! - in TestSuite
6140[ERROR] testConnectNoReadClose(com.facebook.airlift.http.client.jetty.TestJettyHttpsClient)  Time elapsed: 5.017 s  <<< FAILURE!
6141java.lang.AssertionError: Expected request to finish quickly expected:<5.01s> to be less than <1.00s>
6142	at com.facebook.airlift.testing.Assertions.fail(Assertions.java:323)
6143	at com.facebook.airlift.testing.Assertions.assertLessThan(Assertions.java:190)
6144	at com.facebook.airlift.http.client.AbstractHttpClientTest.executeRequest(AbstractHttpClientTest.java:887)
6145	at com.facebook.airlift.http.client.AbstractHttpClientTest.testConnectNoReadClose(AbstractHttpClientTest.java:792)
6146	at com.facebook.airlift.http.client.jetty.TestJettyHttpsClient.testConnectNoReadClose(TestJettyHttpsClient.java:115)
6147	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
6148	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
6149	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
6150	at java.lang.reflect.Method.invoke(Method.java:498)
6151	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
6152	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
6153	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
6154	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
6155	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
6156	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
6157	at org.testng.TestRunner.privateRun(TestRunner.java:773)
6158	at org.testng.TestRunner.run(TestRunner.java:623)
6159	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
6160	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
6161	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
6162	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
6163	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
6164	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
6165	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
6166	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
6167	at org.testng.TestNG.run(TestNG.java:1018)
6168	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
6169	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
6170	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
6171	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
6172	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
6173	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
6174	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
6175	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
6176
6177

**Comment by arhimondr** [comment]
@tooptoop4 We would really love to merge this contribution. Could you please sign the CLA?

**Comment by tooptoop4** [comment]
pls take over

**Pull request closed without merging**
