### PR TITLE
Add support for building on Java 11

### PR DESCRIPTION
**Pull request by dnskr**
Fixes issue https://github.com/prestodb/airlift/issues/79

### CODE REVIEW

**Comment by dnskr** [comment]
Depends on PR https://github.com/prestodb/airbase/pull/23

**Comment by dnskr** [comment]
> Depends on PR [prestodb/airbase#23](https://github.com/prestodb/airbase/pull/23)

The issue mitigated by commit https://github.com/prestodb/airlift/pull/80/commits/0577afdae4c0694817a3f7f1f7032cfc85ccfcc3

**Comment by dnskr** [comment]
The project was successfully built on Java 8 and Java 11.

Java 8
```shell
export JAVA_HOME='/usr/lib/jvm/java-8-openjdk-amd64' && mvn clean install
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for airlift 0.212-SNAPSHOT:
[INFO]
[INFO] airlift ............................................ SUCCESS [ 21.331 s]
[INFO] log ................................................ SUCCESS [ 47.936 s]
[INFO] testing ............................................ SUCCESS [ 51.451 s]
[INFO] configuration ...................................... SUCCESS [01:22 min]
[INFO] log-manager ........................................ SUCCESS [ 55.268 s]
[INFO] bootstrap .......................................... SUCCESS [01:02 min]
[INFO] concurrent ......................................... SUCCESS [01:04 min]
[INFO] http-utils ......................................... SUCCESS [ 41.245 s]
[INFO] json ............................................... SUCCESS [01:19 min]
[INFO] stats .............................................. SUCCESS [02:33 min]
[INFO] security ........................................... SUCCESS [ 55.770 s]
[INFO] trace-token ........................................ SUCCESS [ 43.444 s]
[INFO] http-client ........................................ SUCCESS [03:06 min]
[INFO] node ............................................... SUCCESS [ 56.507 s]
[INFO] discovery .......................................... SUCCESS [01:41 min]
[INFO] dbpool ............................................. SUCCESS [01:18 min]
[INFO] event .............................................. SUCCESS [01:35 min]
[INFO] http-server ........................................ SUCCESS [01:58 min]
[INFO] jaxrs .............................................. SUCCESS [01:45 min]
[INFO] jaxrs-testing ...................................... SUCCESS [01:12 min]
[INFO] jmx-http-rpc ....................................... SUCCESS [01:09 min]
[INFO] jmx-http ........................................... SUCCESS [01:19 min]
[INFO] jmx ................................................ SUCCESS [ 59.473 s]
[INFO] launcher ........................................... SUCCESS [  2.521 s]
[INFO] packaging .......................................... SUCCESS [ 36.431 s]
[INFO] skeleton-server .................................... SUCCESS [01:29 min]
[INFO] sample-server ...................................... SUCCESS [01:39 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33:31 min
[INFO] Finished at: 2024-04-27T17:28:27+02:00
[INFO] ------------------------------------------------------------------------
```

Java 11
```shell
export JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64' && mvn clean install
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for airlift 0.212-SNAPSHOT:
[INFO]
[INFO] airlift ............................................ SUCCESS [ 50.904 s]
[INFO] log ................................................ SUCCESS [ 52.386 s]
[INFO] testing ............................................ SUCCESS [ 58.003 s]
[INFO] configuration ...................................... SUCCESS [01:26 min]
[INFO] log-manager ........................................ SUCCESS [01:01 min]
[INFO] bootstrap .......................................... SUCCESS [01:09 min]
[INFO] concurrent ......................................... SUCCESS [01:07 min]
[INFO] http-utils ......................................... SUCCESS [ 41.695 s]
[INFO] json ............................................... SUCCESS [01:23 min]
[INFO] stats .............................................. SUCCESS [02:32 min]
[INFO] security ........................................... SUCCESS [ 58.440 s]
[INFO] trace-token ........................................ SUCCESS [ 44.324 s]
[INFO] http-client ........................................ SUCCESS [03:01 min]
[INFO] node ............................................... SUCCESS [ 51.679 s]
[INFO] discovery .......................................... SUCCESS [01:37 min]
[INFO] dbpool ............................................. SUCCESS [01:16 min]
[INFO] event .............................................. SUCCESS [01:31 min]
[INFO] http-server ........................................ SUCCESS [01:49 min]
[INFO] jaxrs .............................................. SUCCESS [01:42 min]
[INFO] jaxrs-testing ...................................... SUCCESS [01:20 min]
[INFO] jmx-http-rpc ....................................... SUCCESS [01:12 min]
[INFO] jmx-http ........................................... SUCCESS [01:20 min]
[INFO] jmx ................................................ SUCCESS [01:03 min]
[INFO] launcher ........................................... SUCCESS [  2.897 s]
[INFO] packaging .......................................... SUCCESS [ 38.139 s]
[INFO] skeleton-server .................................... SUCCESS [01:26 min]
[INFO] sample-server ...................................... SUCCESS [01:46 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34:33 min
[INFO] Finished at: 2024-04-27T16:52:46+02:00
[INFO] ------------------------------------------------------------------------
```

**Review by tdcmeehan — APPROVED** [review]

**Comment by tdcmeehan** [comment]
Thank you @dnskr!

**Pull request merged**
