### PR TITLE
Update launcher script to use python3

### PR DESCRIPTION
**Pull request by g1y**

### CODE REVIEW

**Comment by g1y** [comment]
I forgot about that, I guess I shouldn't add that in

**Comment by caithagoras** [comment]
Hey @g1y, I'm still seeing 2 commits, and the 2nd commit `Skip over unsupported algorithm ` is unrelated.

**Comment by g1y** [comment]
Removed it and put it in https://github.com/prestodb/airlift/pull/21

**Comment by caithagoras** [comment]
Please rebase when https://github.com/prestodb/airlift/pull/21 is merged. I'll merged the PR once Travis is green.

**Pull request merged**
